import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google"
import Navbar from "@/components/Navbar";
import {ThemeProvider} from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Elisio Cabral",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
          <Navbar/>
          {children}
      </ThemeProvider>
      </body>
      </html>
  );
}
